spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
      #mode: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/db;MODE=MySQL
#    url: jdbc:h2:~/db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    show-sql: true
